# permissions for end users to edit clusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-relocation-service
    app.kubernetes.io/part-of: cluster-relocation-service
    app.kubernetes.io/managed-by: kustomize
  name: clusterconfig-editor-role
rules:
- apiGroups:
  - relocation.openshift.io
  resources:
  - clusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - relocation.openshift.io
  resources:
  - clusterconfigs/status
  verbs:
  - get
