apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: cluster-relocation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
  namespace: ckyster-relocation
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: cluster-relocation
