---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-config-manager
rules:
- apiGroups:
  - relocation.openshift.io
  resources:
  - clusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - relocation.openshift.io
  resources:
  - clusterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - relocation.openshift.io
  resources:
  - clusterconfigs/status
  verbs:
  - get
  - patch
  - update
